# Source to download
backup_source:
  - /home/xyz/some_folder_0
  - /home/xyz/some_folder_1

# Skip selected files or folders
backup_source_skip:
  - /home/xyz/some_folder_0/some_filder_to_skip
  - /home/xyz/some_folder_1/some_filder_to_skip