your_pc_name:
  # Server details
  HOST:       your_remote_host
  USER:       your_remote_user

  # Private key details
  PKEY:       your_private_key
  PASSPHRASE: your_private_key_passphrase

  # Backup/backup compressed target path (absolute)
  BACKUP_DIR:             your_backup_dir
  BACKUP_DIR_COMPRESSED:  your_backup_dir_compressed

# Test user for running tests
TEST_USER:
  # Docker server details
  HOST:       localhost
  USER:       root
  PORT:       2222

  # Docker server password
  PASSWD:     root

  # Private key details
  PKEY:       id_ed25519_docker
  PASSPHRASE: None

  ##################################

  # Backup target path (relative - start from backup tool directory)
  BACKUP_DIR:  backup_tool/backup.nosync

  # Test paths for recursive download (absolute)
  TEST_DIR_SOURCE:    /largefiles

  # Test paths for file download (absolute)
  TEST_FILE_0:          /largefiles/5M_largefile_0
  TEST_FILE_1:          /largefiles/5M_largefile_1
  TEST_FILE_2:          /largefiles/5M_largefile_2

  TEST_FILE_TO_SKIP:    /largefiles/5M_largefile_1

  TEST_FILE_TARGET_SCP: /test_artifacts/scp_call/5M_largefile_0
  TEST_FILE_TARGET_API: /test_artifacts/api_call/5M_largefile_0

  TEST_DIR_TARGET_SCP:  /test_artifacts/scp_call
  TEST_DIR_TARGET_API:  /test_artifacts/api_call

  TEST_DIR_TO_SKIP:     /largefiles/folder_to_skip