your_pc_name:
  # Server details
  HOST:       your_remote_host
  USER:       your_remote_user

  # Private key details
  PKEY:       your_private_key
  PASSPHRASE: your_private_key_passphrase

  # Backup/backup compressed target path (absolute)
  BACKUP_DIR:             your_backup_dir
  BACKUP_DIR_COMPRESSED:  your_backup_dir_compressed

# Test user for running tests
TEST_USER:
  # Docker server details
  HOST:       localhost
  USER:       root
  PORT:       2222

  # Docker server password
  PASSWD:     root

  # Private key details
  PKEY:       /Users/krzysztofbrzozowski/Documents/PROJECTS/SOFTWARE/backup_tool/tests/id_ed25519_docker
  PASSPHRASE: None

  ##################################

  # Backup target path (absolute)
#  BACKUP_DIR: your_test_destination
#
#  # Test paths for file download (absolute)
#  TEST_FILE_0: your_test_source/largefiles/5M_largefile_0
#  TEST_FILE_1: your_test_source/largefiles/5M_largefile_1
#  TEST_FILE_2: your_test_source/largefiles/5M_largefile_2
#
#  TEST_FILE_TARGET_SCP: your_test_destination_for/scp_call/5M_largefile_0
#  TEST_FILE_TARGET_API: your_test_destination_for/api_call/5M_largefile_0
#
#  TEST_FILE_TO_SKIP: your_test_source/largefiles/5M_largefile_1
#
#  # Test paths for recursive download (absolute)
#  TEST_DIR_SOURCE: your_test_source/largefiles
#  TEST_DIR_TARGET_SCP: your_test_destination_for/scp_call
#  TEST_DIR_TARGET_API: your_test_destination_for/api_call
#
#  TEST_DIR_TO_SKIP: your_test_source/largefiles/folder_to_skip
  BACKUP_DIR: /Users/krzysztofbrzozowski/Documents/PROJECTS/SOFTWARE/backup_tool/backup.nosync

  # Test paths for file download (absolute)
  TEST_FILE_0: /home/testuser/largefiles/5M_largefile_0
  TEST_FILE_1: /home/testuser/largefiles/5M_largefile_1
  TEST_FILE_2: /home/testuser/largefiles/5M_largefile_2

  TEST_FILE_TARGET_SCP: /Users/krzysztofbrzozowski/Documents/PROJECTS/SOFTWARE/backup_tool/backup.nosync/test_artifacts/scp_call/5M_largefile_0
  TEST_FILE_TARGET_API: /Users/krzysztofbrzozowski/Documents/PROJECTS/SOFTWARE/backup_tool/backup.nosync/test_artifacts/api_call/5M_largefile_0

  TEST_FILE_TO_SKIP: /home/testuser/largefiles/5M_largefile_1

  # Test paths for recursive download (absolute)
  TEST_DIR_SOURCE:      /home/testuser/largefiles
  TEST_DIR_TARGET_SCP:  /Users/krzysztofbrzozowski/Documents/PROJECTS/SOFTWARE/backup_tool/backup.nosync/test_artifacts/scp_call
  TEST_DIR_TARGET_API:  /Users/krzysztofbrzozowski/Documents/PROJECTS/SOFTWARE/backup_tool/backup.nosync/test_artifacts/api_call

  TEST_DIR_TO_SKIP:     /home/testuser/largefiles/folder_to_skip