your_pc_name:
  # Server details
  HOST:       your_remote_host
  USER:       your_remote_user

  # Private key details
  PKEY:       your_private_key
  PASSPHRASE: your_private_key_passphrase

  # Backup/backup compressed target path (absolute)
  BACKUP_DIR:             your_backup_dir
  BACKUP_DIR_COMPRESSED:  your_backup_dir_compressed

# Test user for running tests
TEST_USER:
  # Docker server details
  HOST:       localhost
  USER:       root
  PORT:       2222

  # Docker server password
  PASSWD:     root

  # Private key details
  PKEY:       tmp/id_ed25519_docker
  PASSPHRASE: None

  ##################################

  # Backup target path
  BACKUP_DIR:     backup.nosync

  # Test paths for recursive download (absolute)
  TEST_DIR_SOURCE:              largefiles

  # Test paths for file download
  TEST_FILE_0:                  largefile_0
  TEST_FILE_1:                  largefile_1
  TEST_FILE_2:                  largefile_2

  TEST_FILE_TO_SKIP:            file_to_skip_0
  TEST_DIR_TO_SKIP:
    - folder_to_skip
    - largefiles_upload

  DOWNLOAD_TEST_LOCATION_SCP:   test_artifacts/scp_call
  DOWNLOAD_TEST_LOCATION_API:   test_artifacts/api_call

  # temporary folder
  TMP_DIR:                      tmp

  # Test path for recursive upload
  TEST_DIR_UPLOAD_SOURCE:       largefiles_upload

  # Test paths for file upload
  TEST_FILE_UPLOAD_0:           largefile_upload_0
  TEST_FILE_UPLOAD_1:           largefile_upload_1
  TEST_FILE_UPLOAD_2:           largefile_upload_2
