your_pc_name:
  # Server details
  HOST:       your_remote_host
  USER:       your_remote_user

  # Private key details
  PKEY:       your_private_key
  PASSPHRASE: your_private_key_passphrase

  # Backup target path (absolute)
  BACKUP_DIR: your_backup_dir

# Test user for running tests
TEST_USER:
  # Server details
  HOST:       your_remote_test_host
  USER:       your_remote_test_user

  # Private key details
  PKEY:       your_private_key_for_test
  PASSPHRASE: your_private_key_passphrase_for_test

  # Backup target path (absolute)
  BACKUP_DIR: your_test_destination

  # Test paths for file download (absolute)
  TEST_FILE_0: your_test_source/largefiles/5M_largefile_0
  TEST_FILE_1: your_test_source/largefiles/5M_largefile_1
  TEST_FILE_2: your_test_source/largefiles/5M_largefile_2

  TEST_FILE_TARGET_SCP: your_test_destination_for/scp_call/5M_largefile_0
  TEST_FILE_TARGET_API: your_test_destination_for/api_call/5M_largefile_0

  TEST_FILE_TO_SKIP: your_test_source/largefiles/5M_largefile_1

  # Test paths for recursive download (absolute)
  TEST_DIR_SOURCE: your_test_source/largefiles
  TEST_DIR_TARGET_SCP: your_test_destination_for/scp_call
  TEST_DIR_TARGET_API: your_test_destination_for/api_call

  TEST_DIR_TO_SKIP: your_test_source/largefiles/folder_to_skip