name: tests
on: push

jobs:
#  create-test-container:
#    runs-on: ubuntu-latest
#    name: Build SSH and SCP test server
#    steps:
#      - name: checkout
#        uses: actions/checkout@v3
#      - name: Build SSH and SCP test server
#        uses: ./.github/build_test_server_mocker

  tests:
    runs-on: ubuntu-latest
#    container: python:3.11.1

    steps:
      - uses: actions/checkout@v3
      - shell: bash
        env:
          docker_pkey: ${{ secrets.DOCKER_PKEY }}
        run: |
          .github/workflows/prepare_server_test_files.sh "$docker_pkey"

      - name: Install SCP client
        run: sudo apt-get -y install openssh-client

      - name: Run local SSH server from Docker
        run: docker-compose --file .github/workflows/docker-files/docker-compose.yaml up -d

      - name: Test SCP
        run: scp -v -r -P 2222 -i tmp/id_ed25519_docker root@localhost:/largefiles/5M_largefile_0 .

      - name: Install all dependencies for Python
        run: python run.py --install

      - name: Run tests
        run: python run.py --pytest tests/test_functional.py