name: tests
on: push

jobs:
#  create-test-container:
#    runs-on: ubuntu-latest
#    name: Build SSH and SCP test server
#    steps:
#      - name: checkout
#        uses: actions/checkout@v3
#      - name: Build SSH and SCP test server
#        uses: ./.github/build_test_server_mocker

  tests:
    runs-on: ubuntu-latest
#    container: python:3.11.1

    steps:
      - uses: actions/checkout@v3
#      - name: Build SSH and SCP test server
#        uses: ./.github/build_test_server_mocker
      - run: docker run -p 22:22 .
#      - run: docker-compose up
      - run: python run.py --install
      - run: python run.py --pytest tests/test_functional.py