name: tests
on: push

jobs:
#  create-test-container:
#    runs-on: ubuntu-latest
#    name: Build SSH and SCP test server
#    steps:
#      - name: checkout
#        uses: actions/checkout@v3
#      - name: Build SSH and SCP test server
#        uses: ./.github/build_test_server_mocker

  tests:
    runs-on: ubuntu-latest
#    container: python:3.11.1

    steps:
      - uses: actions/checkout@v3
      - shell: bash
        env:
          docker_pkey: ${{ secrets.DOCKER_PKEY }}
        run: |
          .github/workflows/prepare_server_test_files.sh docker_pkey

#      - run: docker-compose --file .github/workflows/docker-compose.yaml up -d
#      - run: python run.py --install
#      - run: python run.py --pytest tests/test_functional.py