name: tests
on: push

jobs:
  tests:
    runs-on: ubuntu-latest
#    container: python:3.11.1

    steps:
      - uses: actions/checkout@v3
      - shell: bash
        env:
          docker_pkey: ${{ secrets.DOCKER_PKEY }}
        run: |
          .github/workflows/prepare_server_test_files.sh "$docker_pkey"
          sudo chmod 600 tmp/id_ed25519_docker

      - name: Install SCP client
        run: sudo apt-get -y install openssh-client

      - name: Run local SSH server from Docker
        run: docker-compose --file .github/workflows/docker-files/docker-compose.yaml up -d

      - name: Install all dependencies for Python
        run: python run.py --install

      - name: Run tests
        run: python run.py --pytest tests/test_functional.py