name: tests
on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    container: python:3.11.1
    runs:
      using: 'docker'
      image: 'tests/Dockerfile'

    steps:
      - uses: actions/checkout@v3
      - run: python run.py --install
      - run: python run.py --pytest tests/test_functional.py