name: tests
on: push

jobs:
  create-test-container:
      runs-on: ubuntu-latest
      container:
        image: tests/Dockerfile

  tests:
    runs-on: ubuntu-latest
    container: python:3.11.1

    steps:
      - uses: actions/checkout@v3
      - run: python run.py --install
      - run: python run.py --pytest tests/test_functional.py